# Generated by Django 4.0.1 on 2022-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('newsIntereactedWith', models.ManyToManyField(related_name='readers_interacted', to='news.News')),
                ('newsSeen', models.ManyToManyField(related_name='readers', to='news.News')),
            ],
        ),
    ]
