# Generated by Django 4.0.1 on 2023-01-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
