# Generated by Django 4.0.1 on 2022-11-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_user_newinteractedwith_alter_user_newsseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='read_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
