# Generated by Django 4.0.1 on 2022-11-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='news.Interest'),
        ),
    ]
