# Generated by Django 4.0.1 on 2022-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='website_favicon',
            field=models.URLField(default='https://media.istockphoto.com/vectors/news-vector-id918880270?k=20&m=918880270&s=612x612&w=0&h=bDcgr9jhiRYCPMUhVdLKD5ouIc5daM4qMcaPPapppQI='),
        ),
        migrations.AddField(
            model_name='news',
            name='website_name',
            field=models.TextField(default='Unknown'),
        ),
    ]
