# Generated by Django 4.0.1 on 2023-01-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_website_favicon_news_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
