# Generated by Django 4.0.1 on 2023-04-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_categories_alter_news_entities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news', to='news.website'),
        ),
    ]
