# Generated by Django 4.0.1 on 2023-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_website_class_of_smallest_article_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
