# Generated by Django 4.0.1 on 2023-02-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_entities'),
        ('authentication', '0002_user_liked_news_user_saved_news_user_shared_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_news',
            field=models.ManyToManyField(related_name='dislikers', to='news.News', verbose_name='news disliked'),
        ),
    ]
