# Generated by Django 4.0.1 on 2023-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_disliked_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notification_token',
            field=models.CharField(default='', max_length=50, verbose_name='Push Notification Token'),
        ),
    ]
